/*
 * This file is generated by jOOQ.
 */
package eu.panic.gameminerservice.generatedClasses.tables.records;


import eu.panic.gameminerservice.generatedClasses.tables.MessagesTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesTableRecord extends UpdatableRecordImpl<MessagesTableRecord> implements Record5<Long, String, Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.messages_table.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.messages_table.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.messages_table.message</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.messages_table.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.messages_table.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.messages_table.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.messages_table.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.messages_table.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.messages_table.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.messages_table.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Long, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Long, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MessagesTable.MESSAGES_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return MessagesTable.MESSAGES_TABLE.MESSAGE;
    }

    @Override
    public Field<Long> field3() {
        return MessagesTable.MESSAGES_TABLE.TIMESTAMP;
    }

    @Override
    public Field<String> field4() {
        return MessagesTable.MESSAGES_TABLE.TYPE;
    }

    @Override
    public Field<String> field5() {
        return MessagesTable.MESSAGES_TABLE.USERNAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMessage();
    }

    @Override
    public Long component3() {
        return getTimestamp();
    }

    @Override
    public String component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getUsername();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMessage();
    }

    @Override
    public Long value3() {
        return getTimestamp();
    }

    @Override
    public String value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getUsername();
    }

    @Override
    public MessagesTableRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MessagesTableRecord value2(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public MessagesTableRecord value3(Long value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public MessagesTableRecord value4(String value) {
        setType(value);
        return this;
    }

    @Override
    public MessagesTableRecord value5(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public MessagesTableRecord values(Long value1, String value2, Long value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagesTableRecord
     */
    public MessagesTableRecord() {
        super(MessagesTable.MESSAGES_TABLE);
    }

    /**
     * Create a detached, initialised MessagesTableRecord
     */
    public MessagesTableRecord(Long id, String message, Long timestamp, String type, String username) {
        super(MessagesTable.MESSAGES_TABLE);

        setId(id);
        setMessage(message);
        setTimestamp(timestamp);
        setType(type);
        setUsername(username);
        resetChangedOnNotNull();
    }
}
