/*
 * This file is generated by jOOQ.
 */
package eu.panic.gameovergoservice.generatedClasses.tables.records;


import eu.panic.gameovergoservice.generatedClasses.tables.MessagesTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesTableRecord extends UpdatableRecordImpl<MessagesTableRecord> implements Record5<Integer, String, String, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.messages_table.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.messages_table.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.messages_table.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.messages_table.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.messages_table.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.messages_table.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.messages_table.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.messages_table.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.messages_table.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.messages_table.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MessagesTable.MESSAGES_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return MessagesTable.MESSAGES_TABLE.TYPE;
    }

    @Override
    public Field<String> field3() {
        return MessagesTable.MESSAGES_TABLE.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return MessagesTable.MESSAGES_TABLE.MESSAGE;
    }

    @Override
    public Field<Long> field5() {
        return MessagesTable.MESSAGES_TABLE.TIMESTAMP;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getMessage();
    }

    @Override
    public Long component5() {
        return getTimestamp();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getMessage();
    }

    @Override
    public Long value5() {
        return getTimestamp();
    }

    @Override
    public MessagesTableRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MessagesTableRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public MessagesTableRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public MessagesTableRecord value4(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public MessagesTableRecord value5(Long value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public MessagesTableRecord values(Integer value1, String value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagesTableRecord
     */
    public MessagesTableRecord() {
        super(MessagesTable.MESSAGES_TABLE);
    }

    /**
     * Create a detached, initialised MessagesTableRecord
     */
    public MessagesTableRecord(Integer id, String type, String username, String message, Long timestamp) {
        super(MessagesTable.MESSAGES_TABLE);

        setId(id);
        setType(type);
        setUsername(username);
        setMessage(message);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }
}
