/*
 * This file is generated by jOOQ.
 */
package eu.panic.gamecrashservice.generatedClasses;


import eu.panic.gamecrashservice.generatedClasses.tables.FlywaySchemaHistory;
import eu.panic.gamecrashservice.generatedClasses.tables.GamesTable;
import eu.panic.gamecrashservice.generatedClasses.tables.MessagesTable;
import eu.panic.gamecrashservice.generatedClasses.tables.ReplenishmentsTable;
import eu.panic.gamecrashservice.generatedClasses.tables.SignInHistoryTable;
import eu.panic.gamecrashservice.generatedClasses.tables.UsersTable;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.games_table</code>.
     */
    public static final GamesTable GAMES_TABLE = GamesTable.GAMES_TABLE;

    /**
     * The table <code>public.messages_table</code>.
     */
    public static final MessagesTable MESSAGES_TABLE = MessagesTable.MESSAGES_TABLE;

    /**
     * The table <code>public.replenishments_table</code>.
     */
    public static final ReplenishmentsTable REPLENISHMENTS_TABLE = ReplenishmentsTable.REPLENISHMENTS_TABLE;

    /**
     * The table <code>public.sign_in_history_table</code>.
     */
    public static final SignInHistoryTable SIGN_IN_HISTORY_TABLE = SignInHistoryTable.SIGN_IN_HISTORY_TABLE;

    /**
     * The table <code>public.users_table</code>.
     */
    public static final UsersTable USERS_TABLE = UsersTable.USERS_TABLE;
}
