/*
 * This file is generated by jOOQ.
 */
package eu.panic.gameminerservice.generatedClasses.tables;


import eu.panic.gameminerservice.generatedClasses.Keys;
import eu.panic.gameminerservice.generatedClasses.Public;
import eu.panic.gameminerservice.generatedClasses.tables.records.NotificationsTableRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationsTable extends TableImpl<NotificationsTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.notifications_table</code>
     */
    public static final NotificationsTable NOTIFICATIONS_TABLE = new NotificationsTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationsTableRecord> getRecordType() {
        return NotificationsTableRecord.class;
    }

    /**
     * The column <code>public.notifications_table.id</code>.
     */
    public final TableField<NotificationsTableRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.notifications_table.is_watched</code>.
     */
    public final TableField<NotificationsTableRecord, Boolean> IS_WATCHED = createField(DSL.name("is_watched"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.notifications_table.message</code>.
     */
    public final TableField<NotificationsTableRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.notifications_table.timestamp</code>.
     */
    public final TableField<NotificationsTableRecord, Long> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.notifications_table.username</code>.
     */
    public final TableField<NotificationsTableRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(255), this, "");

    private NotificationsTable(Name alias, Table<NotificationsTableRecord> aliased) {
        this(alias, aliased, null);
    }

    private NotificationsTable(Name alias, Table<NotificationsTableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.notifications_table</code> table reference
     */
    public NotificationsTable(String alias) {
        this(DSL.name(alias), NOTIFICATIONS_TABLE);
    }

    /**
     * Create an aliased <code>public.notifications_table</code> table reference
     */
    public NotificationsTable(Name alias) {
        this(alias, NOTIFICATIONS_TABLE);
    }

    /**
     * Create a <code>public.notifications_table</code> table reference
     */
    public NotificationsTable() {
        this(DSL.name("notifications_table"), null);
    }

    public <O extends Record> NotificationsTable(Table<O> child, ForeignKey<O, NotificationsTableRecord> key) {
        super(child, key, NOTIFICATIONS_TABLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<NotificationsTableRecord, Long> getIdentity() {
        return (Identity<NotificationsTableRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<NotificationsTableRecord> getPrimaryKey() {
        return Keys.NOTIFICATIONS_TABLE_PKEY;
    }

    @Override
    public NotificationsTable as(String alias) {
        return new NotificationsTable(DSL.name(alias), this);
    }

    @Override
    public NotificationsTable as(Name alias) {
        return new NotificationsTable(alias, this);
    }

    @Override
    public NotificationsTable as(Table<?> alias) {
        return new NotificationsTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationsTable rename(String name) {
        return new NotificationsTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationsTable rename(Name name) {
        return new NotificationsTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NotificationsTable rename(Table<?> name) {
        return new NotificationsTable(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Boolean, String, Long, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super Boolean, ? super String, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super Boolean, ? super String, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
